### ISSUE TITLE
Problems with data from Q-Exactive

### ISSUE THREAD

**Issue by odrangel7** [zamboni-lab/SLAW#10] opened 2021-12-16 13:43 UTC
Hi,

Thanks for your work. I started to test the software, but I faced some issues. First, my data is from a Q-exactive and converted using MSconvert. We run the FullMS using both polarities and thus i need to split into two different batches.

When I ran using the suggested parameters, I found that it goes through all the processes, but it did not detect any ion in the data as i can see from the empty peak lists. I checked, and I was using the OpenMS algorithm, then I changed to CENTWAVE, and it worked adequately as it generated the lists and the final files. However, when I checked the MFG file, I found out that the data is weird, it assigned precursor masses out of the range, and the RT is also completely wrong.  I tried using the ADAP algorithm but i got the same results as with the ADAP. Could be related to the conversion of the mzML files? 

Thanks, 
Oscar

**Comment by adelabriere** [comment] 2021-12-16 13:50
Hi,

It is very surprising, there is no way for SLAW to generate precursor mass outside of the mass range. 

1.) Are your data centroid or profile ? openMS won t run if your data is profile.
2.) Could you run it with the debug tag : -e LOGGING=DEBUG and paste the output here ?
3.)Could you also paster the parameters file ?

Thanks.

**Comment by odrangel7** [comment] 2021-12-17 07:18
Thanks for the quick reply.

Look, i checked my files twice and they are centroid (i centroided them using MSconvert). Here i attach the debug log(from CENTWAVE and openMS), the parameters, the MGF generated using CENTWAVE and the matrices. 

[debugandextras.zip](https://github.com/zamboni-lab/SLAW/files/7733280/debugandextras.zip)

I will try converting my files again using a different method and will come if i get a different output.

Thanks!

**Comment by adelabriere** [comment] 2021-12-17 08:11
Thanks you very much @odrangel7  you actually spotted a bug introduced 15 day ago.

I just fixed it in [6cc0440b70a62f3868f02d568f5baf4d7fddf119](https://github.com/zamboni-lab/SLAW/commit/6cc0440b70a62f3868f02d568f5baf4d7fddf119). Just pull `adelabriere/slaw:dev` or `adelabriere/slaw:latest` and the issue of incorrect precursor masses should be fixed.

Centwave is complaining that your file are in profile mode: 
`In .local(object, ...) :\
  It looks like this file is in profile mode. centWave can process only centroid mode data !\`
There is clearly something strange with your file, I can try to see if I find a solution if you give me access to one the mzML and raw file. openMS is running and detecting 0 mass traces, which is very strange as centwave detect mass traces with similar parameters.

You are also using a very low memory, I guess that you are using docker on windows, maybe look at the resources tab in Docker desktop to increase it:[https://docs.docker.com/desktop/windows/](https://docs.docker.com/desktop/windows/)

**Comment by odrangel7** [comment] 2021-12-17 08:59
Thanks @adelabriere 

I am using in an old Macbook pro (until i can install docker in the pc from work) and thus it is "slow". I will change some of the parameters anyway

Here i attach the raw file and the converted file.
https://www.dropbox.com/t/ChWdGHR711tdGQCp

I did the process three times but with the same results. I realized about the centroid/profile issue, but it is very strange as when i open the file in mzmine it says it is a centroid file. I was wondering if could be related to any issue with the language format of the system in which i converted the files or so?

Thanks again

**Comment by adelabriere** [comment] 2021-12-17 12:49
Sorry @odrangel7 , I just realized that I missed a crucial information, your data contain both polarities, negative and positive. You need to split them using msconvert to be able to process them with SLAW. You can do that with a msconvert filter.

Sadly SLAW only handle single polarity data, and the result from centwave are probably of very strange quality.

Create two batches with of files one positive and one negative and process each independently with SLAW if you want to use it. Sadly there is no capability for having both polarity at the same time.

**Comment by odrangel7** [comment] 2021-12-20 14:35
Hi again,Following the issue. The original raw data is in both polarities but the converted data that i included is in single mode. I did already what you metioned (splitting in two batches) and the results were what i attached (analysis using files containing only one polarity mode)El 17 dic. 2021, a las 13:50, Alexis Delabriere ***@***.***> escribieron:Sorry @odrangel7 , I just realized that I missed a crucial information, your data contain both polarities, negative and positive. You need to split them using msconvert to be able to process them with SLAW. You can do that with a msconvert filter.Sadly SLAW only handle single polarity data, and the result from centwave are probably of very strange quality.Create two batches with of files one positive and one negative and process each independently with SLAW if you want to use it. Sadly there is no capability for having both polarity at the same time.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by odrangel7** [comment] 2022-02-07 19:19
Hi again @adelabriere 
I was wondering if you have any hint with my issue. Here I attach the files that I am using again. I still get the same error. Using openMS it doesn't detect peaks and with centwave the output is strange and I get the message that the data is profile

https://www.dropbox.com/t/d06JbwBhVCZS49SB

**Comment by odrangel7** [comment] 2022-03-03 12:22
Hi,

Sorry for the late response, I was busy with experiments and so. Here are some files which present the error.

https://www.dropbox.com/t/S8YwtfHekeuWccmP

As mentioned before, this files are converted from the original Thermo raw files and split (as we run in both polarities) so I have one for each mode. When processing with the OpenMS I got empty datamatrices, when working with centwave it notifies an error during the processing "it looks that your file is in profile mode". Then sometimes I can finish the processing and other times I get an error during it.

**Comment by htmonkey** [comment] 2022-03-03 14:14
I just ran the optimization, with centwave and openMS. In both cases, all went fine. I used the default parameter.txt generated by SLAW, and changed noise_level_ms1
=50 and need_optimization=true. With openMS, the final data matrix includes ca. 4100 features. With CW, I get 15461 features. All matrices are complete, and the MGFs are also correct. 

In other words: everything looks fine. I can't reproduce your problem. I am pasting the optimized parameter files for your data below. I hope they will help.
[parameters.txt](https://github.com/zamboni-lab/SLAW/files/8178466/parameters.txt)
[parameters.txt](https://github.com/zamboni-lab/SLAW/files/8178470/parameters.txt)

**Comment by odrangel7** [comment] 2022-03-03 21:07
Thank you very much for both files @htmonkey . This time everything worked pretty well. I used the parameters you provided and got data matrices in both files. Here I paste the logs. As you can see in the centwave I got these error messages. However, everything worked well
[log.txt](https://github.com/zamboni-lab/SLAW/files/8181138/log.txt)
[logOpenMS.txt](https://github.com/zamboni-lab/SLAW/files/8181139/logOpenMS.txt)

It is weird but at least it seems that it is solved. Thanks!

**Closed** 2022-03-04 16:40 UTC
